### ISSUE TITLE
Poor quality of components when theme is applied

### ISSUE THREAD

**Issue by tanguyhardion** [vincenzopalazzo/material-ui-swing#196] opened 2022-12-25 23:22 UTC
No matter what theme I apply, Swing components such as Button, RadioButton and ToggleButton (and all of the others I believe) are terribly rendered *(screenshot below)*. Not sure what could cause it, I'm using version 1.1.4, Java 18 and IntelliJ 2022.

![attachment](https://user-images.githubusercontent.com/45904983/209484354-6dd73fc4-bdee-418a-ab02-ec764bf299b4.png)

**Comment by vincenzopalazzo** [comment] 2022-12-26 16:23
Mh that it is interesting, I think there is some problem with this method here https://github.com/vincenzopalazzo/material-ui-swing/blob/master/src/main/java/mdlaf/utils/MaterialDrawingUtils.java#L40 bit not sure that kind of problem. 

I did not test it with the latest version of java, but there is some why to reproduce it? From my experience this kind of problem are machine related, so I guess without this info I can not help you much.

Maybe I can guide to to find a patch and open a PR to fix it

**Comment by tanguyhardion** [comment] 2022-12-26 18:22
[Here](https://file.io/g1F14kqYhsW2) is a sample IntelliJ project I just made, and below my output when running the **MainWindow** class. JDK is set to latest (19). That should tell us whether it's machine-related or not.
![attachment](https://user-images.githubusercontent.com/45904983/209574594-d5b67b32-d2ad-44be-bc53-fb585a56e30f.png)

**Comment by vincenzopalazzo** [comment] 2022-12-27 09:02
I am always reluctant to download unverified zip from a source,
I'm happy to give a run to you application if you create a zip.

However this do not required a custom application, but
you can simple using the Demo inside the library.

An the following wiki show what In my system https://github.com/vincenzopalazzo/material-ui-swing/wiki/Screenshots

**Comment by tanguyhardion** [comment] 2022-12-27 09:58
I tested the app I provided on another machine and it turns out that every component was displayed properly. I guess it has to be a problem on my end, something related to graphics probably.

**Comment by vincenzopalazzo** [comment] 2022-12-27 12:47
>I guess it has to be a problem on my end, something related to graphics probably.

Hight quality graphics is not tested because I do not have the hardware to test it, but I'm pretty sure that with some google research and the pointer that I give you to the paint method you can find a work solution and maybe submit a patch.

For the moment I will close this issue

**Closed by vincenzopalazzo** 2022-12-27 12:47 UTC
Labels: bug, conversation, mentoring
