### ISSUE TITLE
Font - Last Letter Cut-off (using Roboto font)

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#138] opened 2020-05-17 01:57 UTC
On several screens, it is observed that the last letter gets cut-off.
One observation of it is in File Chooser

![image (2)](https://user-images.githubusercontent.com/49419742/82133964-d872f800-97a6-11ea-8dac-1804c7f2ff08.png)
![image (1)](https://user-images.githubusercontent.com/49419742/82133965-d90b8e80-97a6-11ea-90d6-077846d3d996.png)

While another one is on a regular panel (see text at the bottom "Total records...." where number "4" is cut off...

![image](https://user-images.githubusercontent.com/49419742/82133973-e9bc0480-97a6-11ea-8d82-211b10476259.png)

**Comment by vincenzopalazzo** [comment] 2020-05-17 02:50
Hi @zanderson9,

Unfortunately, I'm not able to reproduce the bug, this is my effect

![Screen Shot 2020-05-16 at 7 41 33 PM](https://user-images.githubusercontent.com/17150045/82134524-c9437880-97ad-11ea-8a0a-3ba4bee681f2.png)

The demo with method call `getFont(typeFont, false)` is [here](https://drive.google.com/open?id=10tGVCW_9DYV5o_-9AwEUoiVzsbclXRTI)

P.S: The only cut-of that I see is because the line is EOF.

JDK: 1.8
OS: MAC_OS
material-lib version: rc4 (the next rc3 in this Monday)

**Comment by vincenzopalazzo** [comment] 2020-06-06 05:07
Hi @zanderson9,

I change the label from requested more details to enhancement because the problem is the JDK8 and with the JetBrains JDK this bug was fixed. Maybe I can try to support in the future this problem inside the font class.

But at the moment this problem lives.

**Comment by vincenzopalazzo** [comment] 2020-08-03 11:33
I'm closing this issue because is marked as duplicate. The issue to describe this problem is this https://github.com/vincenzopalazzo/material-ui-swing/issues/142

**Closed by vincenzopalazzo** 2020-08-03 11:33 UTC
Labels: duplicate
