### ISSUE TITLE
JButton - no visual indicator when button is in focus 

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#21] opened 2019-04-09 01:43 UTC
when using material-ui-swing, it was noticed that there is no visual indicator to a user when a button is in focus. For example if user tabs through buttons in a window, there is no visual effect that a button received focus. Can this feature be implemented under material-ui-swing?

**Comment by vincenzopalazzo** [comment] 2019-04-09 08:18
Hi @zanderson9,
Can you give me an example of the you effect want

**Comment by vincenzopalazzo** [comment] 2019-04-09 22:34
Hi @zanderson9,

Do you like this effect? 
![](https://media.giphy.com/media/2vqdj2iCIy9XaXESuk/giphy.gif)

**Comment by zanderson9** [comment] 2019-04-09 23:59
Vincent, yes thank you, the effect you are suggesting is great.

**Comment by srcarter3** [comment] 2019-04-10 20:30
Hi Vincent,
It appears that the buttons from your library, are skipped over entirely when tabbing through components.
I've attached a before and after Tab select in our previous look and feel.
This is achieved by pressing Tab until the JButton is the component in focus, or selected?  I'm not sure if focus is technically the right state.
Hope the images help.
![beforeTab](https://user-images.githubusercontent.com/21114460/55911097-cb8fd800-5b94-11e9-944c-cfd7b0649883.png)
![afterTab](https://user-images.githubusercontent.com/21114460/55911098-cb8fd800-5b94-11e9-924a-08372f5ecae1.png)

**Comment by vincenzopalazzo** [comment] 2019-04-10 20:55
Hi @srcarter3,

Yes the effect should be this. when you effect tab the border button change color, the color default is black but in next official relaise I will add a constant into UIDefault.

I understand your problem? if I not understand your problem your use an example with jar into my project, her position is libs/file.jar

**Comment by srcarter3** [comment] 2019-04-10 20:58
Hi Vincent,

Yes, that would be nice. 
The jar that you gave my coworker, currently does not allow tabbing to select the button. 
When I press tab, it skips the button entirely.
Does that make sense?

**Comment by srcarter3** [comment] 2019-04-10 21:01
Also, would there be anyway to make the outline be around the text, not the edge of the component?  It is easier to see with any color background, if the outline is "inside the button".  Maybe something like the attached photo?
![Screenshot](https://user-images.githubusercontent.com/21114460/55913308-304d3180-5b99-11e9-9f2e-21ff8ac43385.png)

**Comment by vincenzopalazzo** [comment] 2019-04-10 21:09
@zanderson9, in material-ui-swing, in default is disabled, or you enable in all button whit button.setFocusable(true) or you change a value into UIDefaulti, whit this code  
`UIManager.put("Button.focusable", true);`

For the border into text, is the effect don't like me, but I would like to add an effect like that of gmail, because the outline of the text knows to me of ancient, but if you want I can try to add this effect too

**Comment by srcarter3** [comment] 2019-04-10 21:21
Okay, setting UIManager.put("Button.focusable", true); worked and now it recognizes the tabs. 

One thing though, related to the "Default Button" look.  The "focus" look and "default button" look is the same in your package, and they were distinctly different in the old package.
![Screenshot-4](https://user-images.githubusercontent.com/21114460/55914400-e87bd980-5b9b-11e9-9ded-e98ca695b4ec.png)
![Screenshot-2](https://user-images.githubusercontent.com/21114460/55914401-e87bd980-5b9b-11e9-95d2-662a346e6f87.png)
![Screenshot-3](https://user-images.githubusercontent.com/21114460/55914402-e87bd980-5b9b-11e9-8946-941723d35f03.png)

**Comment by vincenzopalazzo** [comment] 2019-04-10 21:44
@srcarter3, 

Yes the color font, or the changing border color whit color equal button background, I will see examples.

> Maybe changing the font color then? When focused? and have the outline just for the default button? 

The problem is when the button is focused and the button default not have a border, right? and before this effect there was

**Comment by srcarter3** [comment] 2019-04-10 21:47
> The problem is when the button is focused and the button default not have a border, right? and before this effect there was

Yes, previously, it could be default, AND focused.  Or another button could be focused, and the default button still looked like the default.
![Screenshot-6](https://user-images.githubusercontent.com/21114460/55915886-9b9a0200-5b9f-11e9-9292-ad497266a4c3.png)
![Screenshot-5](https://user-images.githubusercontent.com/21114460/55915887-9c329880-5b9f-11e9-920e-77024cc2d7a9.png)

**Comment by vincenzopalazzo** [comment] 2019-04-10 22:23
@zanderson9 I apported the more change, this is the bug, I will work on it calmly

**Comment by zanderson9** [comment] 2019-04-10 22:51
I'd suggest we follow the [guidelines from Material Design on buttons States](https://material.io/design/interaction/states.html)

**Comment by lilili87222** [comment] 2019-04-11 01:01
Yes,Swing focus is ugly，not need to create swing focus state. follow the flat and material skin.

**Comment by vincenzopalazzo** [comment] 2019-04-11 10:54
Hello guys, thanks for your help.
I spent the morning doing tests and I changed the way to highlight the tabulated button, but I couldn't change the default button, for the moment I ask you to resolve otherwise if you have an imminent need for this effect, I can guarantee you that I will work on it but I can't guarantee a fix in the imminent future, so you can generate the focus effect with these constants in the default

```
UIMaganer.put("Button.focusable", false);
UIMaganer.put("Button[focus].background", MaterialColors.COSMO_BLUE);
UIMaganer.put("Button[focus].foreground", Color.DARK_GRAY);
```

sorry if I do not resolved your problem

**Comment by vincenzopalazzo** [comment] 2019-04-11 15:45
Hi @zanderson9 , @srcarter3, @lilili87222 

Hi @ zanderson9, @ srcarter3, @ lilili87222

My previous solution worked, yes but I hadn't calculated the click, in the click all the colors are strange, unfortunately there are too many events, like the hover that makes me jump something, but I thought of adding a line under the text to highlight a main mouse button, unfortunately the limits of my junior programmer allow me to find this solution for the moment, if you want to give me some guidelines or ideas to solve these problems I'm happy.

My problem is that I have no method to interfere with the button's life cycle, in fact I have nothing to interfere with the effect I want to give the button after the end of the action associated with the click, I only have one but it is not called as a last resort and therefore these changes are not successful

Since I never needed to highlight a button with the card, I ask you, is it also the result of another aspect and feeling that after pressing the button this remains in FOCUS? also Metal uses this type of approach and therefore for the moment I stop at this solution if it is good for you.

the constant is used to set the color of the line

`UIManager.put("Button[focus].color", MaterialColors.BLACK);`

I hope I have been helpful

**Comment by zanderson9** [comment] 2019-04-11 18:22
Vincent thank you, we will give it a try. We appreciate you working toward finding the solution!

**Comment by vincenzopalazzo** [comment] 2019-04-11 19:02
@zanderson9 I'm waiting your feedback, if the method not have a bugs, I will try Improve the graphics

**Comment by zanderson9** [comment] 2019-04-11 19:10
Yes, we will test the new jar you built today and will share the feedback asap.
Thank you for your prompt responses to the issues.

**Comment by zanderson9** [comment] 2019-04-11 20:21
verified with new **test jar** - looks good with the Underline effect

**Comment by vincenzopalazzo** [comment] 2019-04-11 20:53
@zanderson9, Good, if the issue is fixed, I closing issue :)

**Closed by vincenzopalazzo** 2019-04-11 20:53 UTC
Labels: bug

**Comment by lilili87222** [comment] 2019-04-12 00:43
This effect is very cool  
https://camo.githubusercontent.com/d5af1ca60cb31e576c07ed996304377d48f3ba1e/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f3437466648593154484150335074374f7a552f67697068792e676966

I do not think you need to add a line under text,That was ugly really

**Comment by zanderson9** [comment] 2019-04-12 01:00
@lilili87222 , could you check the link you posted in your recent Comment, please? It returns "Non-Image content-type returned" error...

**Comment by srcarter3** [comment] 2019-04-12 17:14
I really like the underline for the focus, I think it looks good!  Thank you Vincent.
![focus](https://user-images.githubusercontent.com/21114460/56054459-c1441a00-5d0b-11e9-9edc-dc32f06e345b.png)

**Comment by vincenzopalazzo** [comment] 2019-04-12 18:29
Hi @srcarter3, This is the only solution for the moment, exist more event into jbutton, an example MouseHover but I want to have a better effect, maybe I'll keep working on it and try to maintain backwards compatibility with this version.

I'm glad you like my job
