### ISSUE TITLE
Exception received with custom component JCalendar

### ISSUE THREAD

**Issue by dariopereiradp** [vincenzopalazzo/material-ui-swing#150] opened 2020-09-16 18:22 UTC
Hello! I migrated from material-ui-swing 0.9.6.1 to the newest 1.1.1, and when I try to open a JDateChooser, I get these two kinds of exceptions:

`Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: javax.swing.JTextField cannot be cast to javax.swing.JSpinner$DefaultEditor
	at mdlaf.components.spinner.MaterialSpinnerUI.paint(MaterialSpinnerUI.java:70)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1978)
	at java.awt.Window.paint(Window.java:3906)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

`Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: javax.swing.JComboBox cannot be cast to javax.swing.JSpinner$DefaultEditor
	at mdlaf.components.spinner.MaterialSpinnerUI.paint(MaterialSpinnerUI.java:70)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

The problem is in the MaterialSpinnerUI.java, in the "else" of this method:
    @Override
    public void paint(Graphics g, JComponent c) {
        super.paint(g, c);
        if(!c.isEnabled()){
            ((JSpinner.DefaultEditor)spinner.getEditor()).getTextField().setBackground(spinnerDisableBackground);
        }else{
            ((JSpinner.DefaultEditor)spinner.getEditor()).getTextField().setBackground(spinnerBackground);
        }
    }

What can I do?

(the JCalendar is buggy: I can olny see the days numbers when I hover the mouse over it)

**Comment by vincenzopalazzo** [comment] 2020-09-16 18:37
Hi  @dariopereiradp,

Thanks to reporting this exception, I will work this week and I try to release the fix on Monday, or if you like contribute can you open a PR. The bug is essentially a cast.

You can check if the `spinner.getEditor()` return a correct instance of `DefaultEditor` or in your cases, it returns a JTextField.

But, I want to try to search more about this exception, because if the exception happened in the else, it means that the component is enabled, but in my demo and in the official application this code works fine.

Can you post, an example of your code to reproduce this bug?

>(the JCalendar is buggy: I can only see the days numbers when I hover the mouse over it)

About JCalendar, it doesn't have a bug, but it is not supported at all. There is [this PR](https://github.com/vincenzopalazzo/material-ui-swing/pull/121) that try to support it but is not merged yet. I don't think that I will support the external at the moment but I can say that if you want help you can open a PR.

There is a lot of example to how to add a component inside the library, and it is easy if you like to read the code of calendar component and use a custom theme to customize the library. If you like to learn about how the library offer, can you look [here](https://github.com/material-ui-swing)

If you can send me an example to reproduce this bug, I can help you to continue your work with the library.

Regards.

Vincent.

**Comment by dariopereiradp** [comment] 2020-09-16 19:55
Hi @vincenzopalazzo 

Thanks for the reply!

This is my code:

                `JDateChooser date_nasc = new JDateChooser();
		date_nasc.setLocale(new Locale("pt", "BR"));
		date_nasc.setDateFormatString("dd/MM/yyyy");
		date_nasc.setMaxSelectableDate(new Date());
		date_nasc.setDate(new Date());`

![image](https://user-images.githubusercontent.com/48100453/93380039-0fc8e280-f835-11ea-9b14-3cbe769ff97d.png)

The problem is: I have the JDateChooser. When I click on the calendar button on the right, it should open a calendar, but it only shows this:
![image](https://user-images.githubusercontent.com/48100453/93380373-89f96700-f835-11ea-8a4a-c21a41d4df89.png)
And at this moment, I get the first exception (JTextField).
When I hover the mouse over it, the days start to appear...
![image](https://user-images.githubusercontent.com/48100453/93380710-faa08380-f835-11ea-9148-8cf3a6cc706b.png)

Eclipse points the problem to here:
![image](https://user-images.githubusercontent.com/48100453/93381030-73074480-f836-11ea-9748-d47ea47a9c79.png)

I also noticed that when I select a month through the month selection menu, it works ok:
![image](https://user-images.githubusercontent.com/48100453/93382579-ad71e100-f838-11ea-8557-bef6aeb1e195.png)


I put this on the code: `System.out.println(date_nasc.getDateEditor());` and then I get:  `com.toedter.calendar.JTextFieldDateEditor`
So I guess this may be the problem, or one of the problems?

Update: I made a debug, and I can confirm that `spinner.getEditor()` is returning a JTextField.
![image](https://user-images.githubusercontent.com/48100453/93385206-47875880-f83c-11ea-8a11-f5b3fd20f79c.png)

Best regards!

Dário Pereira

**Comment by vincenzopalazzo** [comment] 2020-09-17 10:41
Hi @dariopereiradp,

This is not a bug of the library but it is some mistake inside the custom library JDateChooser. This is a request of feature for some cases this can be done with the MaterialTheme, but I need more time to look inside the JDateChooser library.

At the moment the material-lib work only with the swing framework, and in others cases we can have some problems like this. But Anyway, If I will find a solution, I will push the new release on Monday!

Thank you to use material library!

**Comment by dariopereiradp** [comment] 2020-09-17 21:23
Hi @vincenzopalazzo ,

Thanks again for your answer.

If it helps in anything, I see that using the 1.1.1-rc1 version and earlier versions, the JDateChooser works fine. But since the 1.1.1-rc2 the problem appears.

Best regards,

Dário Pereira

**Comment by vincenzopalazzo** [comment] 2020-09-18 18:53
Hi @dariopereiradp,

Thanks for this additional information.

Yep, I expect this behavior because I added new code the the `1.1.1-rc2`. I will work on it :-)

**Comment by vincenzopalazzo** [comment] 2020-09-20 10:33
Thanks to contributing in material-ui-swing. This bug is fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.2-rc1.

Good job!

**Closed by vincenzopalazzo** 2020-09-20 10:33 UTC
Labels: bug
