### ISSUE TITLE
JTable - keyboard navigation is lost

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#45] opened 2019-05-04 02:23 UTC
The Material JTable control is not responding to the keyboard input, such as pressing "Up" or "Down" keys to scroll through the rows. Only mouse scrolling with scrollbar is available, but keyboard should be too.
Please include "Up" - "Down" keyboard input to Material JTable to allow navigation through table items.

**Comment by vincenzopalazzo** [comment] 2019-05-04 08:46
Hi @zanderson9, 

The problem is causate to JTable into material-ui-swing is not focusable, you resolve this problem with this code
`table.put("Table.focusable", true); `

I'm closing the problem but I'm waiting your feedback :)

**Closed by vincenzopalazzo** 2019-05-04 08:46 UTC

**Comment by zanderson9** [comment] 2019-05-06 21:32
Worked. Great.
