### ISSUE TITLE
Weird selection placement in tabbedpane when using Right or Left Tabbedpane

### ISSUE THREAD

**Issue by Vodes** [vincenzopalazzo/material-ui-swing#97] opened 2020-01-06 13:17 UTC
Using v1.1.1 Beta but has happened in the versions before aswell.
Using Dialog 12 Font.

Sample picture:

![0QStu5tFrgWWoMQ](https://user-images.githubusercontent.com/48185123/71820345-1e001580-308f-11ea-9357-b708471c1433.png)

**Comment by Vodes** [comment] 2020-01-06 13:17
I know that its really nitpicky but it kind of annoys me xD

**Comment by vincenzopalazzo** [comment] 2020-01-07 11:04
HI @Vodes,

>I know that its really nitpicky but it kind of annoys me xD

I have start to work at this problem from a little time, this is/was a hard work to fix this problem but I think I have arrived to the stable version 2 day a go with this commint

**Comment by zanderson9** [comment] 2020-01-07 21:07
Hi Vincent, this is a comment from Zoya.
I haven't moved JMARS to version 1.1. yet, we are working with 1.0.9, mainly due to TABS issue that we discussed prior. So do you expect that with the updated release of 1.1.1 we will be able to set "thick" TAB underline?

**Comment by vincenzopalazzo** [comment] 2020-01-13 13:55
Hi @zanderson9,

I have the new version of JTabbedPane, with less configuration and above all less bugs.

>I haven't moved JMARS to version 1.1. yet, we are working with 1.0.9, mainly due to TABS issue that we discussed prior.

All know issues inside the JTabbedPane are fixed, but I will need other time to do integration test with the swing application; but version 1.1.1 is coming soon.

>So do you expect that with the updated release of 1.1.1 we will be able to set "thick" TAB underline?

Yes with version 1.1.1 of the library, it will give the possibility to manage the thick of the line in the Tab selected.


PS: I have did a little integration test with JMars and I have some problem; I will need your consulence for reproduce the problem in normal swing application.

@Vodes and @zanderson9 I released with [this link](https://drive.google.com/file/d/1fi8GsRko39xrMvbRT9qDM5Gv6CFjbvAy/view?usp=sharing) the demo with the version library update.

I would like have your feedback on the new style.

/polls 'I like new style' 'I don't like new style'

**Comment by vincenzopalazzo** [comment] 2020-01-13 13:56
/polls 'I like the new style' 'I don't like the new style'

**Comment by zanderson9** [comment] 2020-01-14 00:02
Vincent,

I ran the latest demo. I like the current solution for the TABS!

**Comment by vincenzopalazzo** [comment] 2020-02-24 12:54
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease

**Closed by vincenzopalazzo** 2020-02-24 12:54 UTC
Labels: bug
