### ISSUE TITLE
InternalFrame + TextComponent drawing issue

### ISSUE THREAD

**Issue by jarek-insys** [vincenzopalazzo/material-ui-swing#98] opened 2020-01-13 10:06 UTC
Hi Vincent @vincenzopalazzo,

I noticed an issue when I've 2 internal frames with text component. If you move one frame over another frame: the frame on top has painting from back frame

![image](https://user-images.githubusercontent.com/59824651/72247061-64f08c80-35f4-11ea-9fa6-54467790fb7a.png)

Is that something which can be changed in the configuration or in another way?

**Comment by vincenzopalazzo** [comment] 2020-01-13 13:29
Hi @jarek-insys,

Sorry for the late answer; I have worked on this error, in [this issue](https://github.com/vincenzopalazzo/material-ui-swing/issues/80)

 For work on this problem, I will have the need to a minimum example reproducible, because I will test the bug for start the debugging.

PS: In this period I will have little time because I'm prgrammation a University trip to improve my English. I want to you know that I'm continuing to work in this library but in  January my work will be slow because I have little time; I'm sorry.

Thanks for your time and for your work.

**Comment by jarek-insys** [comment] 2020-01-13 14:27
Hi Vincent @vincenzopalazzo,

As you wish,
Simple Frame with 2 internal frames.

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;

import javax.swing.BorderFactory;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

public class IssueExample {
   static {
      try {
         // UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new
         // mdlaf.themes.MaterialOceanicTheme()));
         UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new mdlaf.themes.MaterialLiteTheme()));
         // UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new
         // mdlaf.themes.JMarsDarkTheme()));
         UIManager.put("Button.mouseHoverEnable", false); // Because the test are more difficulte with effect mouse
                                                          // hover
         JDialog.setDefaultLookAndFeelDecorated(true);
         JFrame.setDefaultLookAndFeelDecorated(false); // not support yet

      } catch (UnsupportedLookAndFeelException e) {
         e.printStackTrace();
      }
   }

   public static void main(String[] args) {
      MainFrameExample frame = new MainFrameExample();
      frame.setVisible(true);
   }
}

class MainFrameExample extends JFrame {
   private static final long serialVersionUID = 1L;

   protected JDesktopPane thisDesktopPane = new JDesktopPane();

   protected int prevWidth = 0;
   protected int prevHeight = 0;

   protected MainFrameExample() {
      this.getContentPane().setLayout(new BorderLayout());

      JPanel p = new JPanel(new BorderLayout());
      p.setBorder(BorderFactory.createLoweredBevelBorder());
      JScrollPane scrollPane = new JScrollPane(thisDesktopPane);
      p.add(scrollPane, BorderLayout.CENTER);
      this.getContentPane().add(p, BorderLayout.CENTER);

      try {
         jbInit();
      } catch (Exception e) {
         e.printStackTrace();
      }
      setDefaultCloseOperation(EXIT_ON_CLOSE);
   }

   private void jbInit() throws Exception {
      this.setTitle("Test internal frame");
      setSize(new Dimension(800, 600));
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosed(java.awt.event.WindowEvent e) {
            System.exit(0);
         }

         public void windowOpened(WindowEvent e) {

            InternalFrameExample frame1 = new InternalFrameExample(1);
            thisDesktopPane.add(frame1, JDesktopPane.DEFAULT_LAYER);
            try {
               frame1.setTitle("Internal 1");
               frame1.setBounds(0, 0, 500, 150);
               frame1.setVisible(true);
               frame1.setSelected(true);
            } catch (PropertyVetoException e1) {
               e1.printStackTrace();
            }

            InternalFrameExample frame2 = new InternalFrameExample(2);
            thisDesktopPane.add(frame2, JDesktopPane.DEFAULT_LAYER);
            try {
               frame2.setTitle("Move me over Internal 1");
               frame2.setBounds(100, 0, 500, 150);
               frame2.setVisible(true);
               frame2.setSelected(true);
            } catch (PropertyVetoException e1) {
               e1.printStackTrace();
            }
         }
      });
   }

   class InternalFrameExample extends JInternalFrame {
      static final long serialVersionUID = 1;

      public InternalFrameExample(int nb) {
         super();
         setResizable(true);
         setMaximizable(true);
         setIconifiable(true);
         setClosable(true);
         setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

         setPreferredSize(new Dimension(500, 150));
         getContentPane().setLayout(null);
         JTextField f1 = new JTextField();
         f1.setText("Text-" + nb);
         f1.setBounds(0, 0, 500, 21);
         getContentPane().add(f1, null);
         pack();
      }
   }
}

**Comment by vincenzopalazzo** [comment] 2020-01-13 21:22
Hi @jarek-insys,

Thanks for your help, I have reproduced the bug.

I will work on the bug, the feature to fix this bug is coming.

**Comment by jarek-insys** [comment] 2020-01-14 12:04
Vincent,

Thanks

P.S.
Probably you didn't notice but
I you switch in demo Look to Java and back Material Style resizing internal windows is also 
working differently than that it was at the beginig but I suppose it is not big problem since
looks are usually not changed in apps

**Comment by vincenzopalazzo** [comment] 2020-01-14 20:16
HI @jarek-insys 

>Probably you didn't notice but
I you switch in demo Look to Java and back Material Style resizing internal windows is also
working differently than that it was at the beginig but I suppose it is not big problem since
looks are usually not changed in apps

Can you give me an example of this to understand?

**Comment by jarek-insys** [comment] 2020-01-15 07:52
Vincent,
1. Start demo normal behave on resize (cannot do screenshot of resize cursor)
![image](https://user-images.githubusercontent.com/59824651/72414985-c68b3500-3773-11ea-9013-2275a56f5188.png)
2. Look & Feel/ Java Look & Feel  - resize ok
3. Look & Feel/ Material Style Look & Feel
![image](https://user-images.githubusercontent.com/59824651/72415163-2d105300-3774-11ea-8ece-daee46bd9318.png)
Abnormal resize
Probably something not installed/uninstalled when switching Looks

I hope clear enough

**Comment by vincenzopalazzo** [comment] 2020-01-15 19:19
Hi @jarek-insys,

Yes, I understand, you mean the type of cursor when it is used the personal TitlePaneUI; I know this problem and this is a little delicate.

I can ask you if you can open a new issue to describe this issue?

**Comment by vincenzopalazzo** [comment] 2020-02-24 12:54
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease

**Closed by vincenzopalazzo** 2020-02-24 12:54 UTC
Labels: bug
