### ISSUE TITLE
JMenuBar - appearance is altered when using test jar you built for us

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#26] opened 2019-04-10 22:44 UTC
Hi Vincent,
i'm using the **test** jar you built for us today ( April 10), which includes fixes to the issues #19-#23. Thank you for this prompt update!

With this new **test** jar, we noticed that one of our controls, JMenuBar, unexpectedly changed its appearance. It was set to have background color #42B3B0 and worked well under the  "**release** 0.9.9" jar. But under the today's **test** jar, the background is _WHITE_.
What possibly changed in the **test** jar that affected JMenuBar background color setting? 
Screens are attached.
**test** jar
![Screenshot1](https://user-images.githubusercontent.com/49419742/55918183-fc790880-5ba6-11e9-89ed-d635a9769270.png)

**release** jar
![Screenshot2](https://user-images.githubusercontent.com/49419742/55918193-04d14380-5ba7-11e9-9479-67fc65c99c03.png)

**Comment by vincenzopalazzo** [comment] 2019-04-10 22:57
Hi @zanderson9, the you jar test are changed most because befoure the material look and feel exstended a MetalLook and feel and now Exend basic look and feel, I wanted to do a test to see if things changed in appearance, with BasicLookAndFell there is more direct contact. I will work on it calmly

**Comment by zanderson9** [comment] 2019-04-10 22:59
Sounds good. Thank you.

**Comment by vincenzopalazzo** [comment] 2019-04-11 10:56
Hi @zanderson9,
I tried to re-import the MetalMenuBar, if it doesn't work I ask you to send me an example to reproduce the bug, let me know

**Comment by vincenzopalazzo** [comment] 2019-04-12 20:20
hi @zanderson9,

This bug is still present?

**Comment by zanderson9** [comment] 2019-04-12 21:25
This bug is not present anymore. @srcarter3 fixed it on our end. Thank you both.

**Comment by vincenzopalazzo** [comment] 2019-04-13 07:53
Hi @zanderson9,
Does the problem persist in the official repo? or the bug not longer exist?

**Comment by zanderson9** [comment] 2019-04-16 21:33
@vincenzopalazzo this is resolved on our end. You can Close this issue. Thank you.

**Comment by vincenzopalazzo** [comment] 2019-04-16 22:28
Hello @zanderson9,

Thanks so much, this bug was resolved whit my commit or the bug is resolved in the your context? 

in other word, the bug not longer exist in the project material-look-and-fell?

**Closed by vincenzopalazzo** 2019-04-16 22:28 UTC
Labels: bug

**Comment by zanderson9** [comment] 2019-04-16 23:12
@vincenzopalazzo, the bug for JMenuBar was resolved in our code by setting the background property on the control. We did not do any change to the library. So I would say, leave the library as is, no changes needed.

**Comment by lilili87222** [comment] 2019-04-17 09:08
All dependence libs  removed from the swing-set3 will be better.

**Comment by vincenzopalazzo** [comment] 2019-04-17 09:54
It takes a long time to remove the libraries because when I tried it sparser exceptions were raised but I will try :) thanks
